version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo:3.2
    networks:
      - pritunl
    ports:
      - "${MONGODB_BIND_PORT}:27017"
    restart: always
    volumes:
      - ./data/db:/data/db
  pritunl:
    container_name: pritunl
    build: .
    image: pritunl
    depends_on:
      - mongo
    networks:
      - pritunl
    ports:
      - "${PRITUNL_BIND_HTTP_PORT}:80"
      - "${PRITUNL_BIND_HTTPS_PORT}:443"
      - "${PRITUNL_BIND_OVPN_PORT}:1194/udp"
    privileged: true
    restart: always

networks:
  pritunl:
